Support b-frames disabling
cloudinary/cloudinary_kotlin pull request #63
Opened 2022-04-12 07:34 UTC by adimiz1

### Brief Summary of Changes
Support disabling b_frames in video codec

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [x] New feature
- [ ] Bug fix
- [x] Adds more tests

#### Are tests included?
- [x] Yes
- [ ] No

#### Reviewer, please note:

#### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

2022-04-18 10:34 UTC, patrick-tolosa commented
We've had a mistake in the specification here, h264 does not support bframes, please implement the h265 video codec

2022-04-18 10:35 UTC, patrick-tolosa requested changes

2022-04-18 10:35 UTC, patrick-tolosa commented on url-gen/src/main/kotlin/com/cloudinary/transformation/transcode/TranscodeActions.kt
> +class H264Codec private constructor(private val profile: VideoCodecProfile? = null, private val level: Any? = null, private val bFrames: Boolean? = null) :
Spec error, we'll need to implement an H265Codec

2022-05-07 18:36 UTC, const-cloudinary requested changes
See Patrick's comment

2022-05-09 05:07 UTC, closed without merging